### ISSUE TITLE
Stays black on Chrome on Android.

### ISSUE THREAD

**Issue by carstenhag** [Sean-Bradley/Oscilloscope#1]
App should be on the newest version.
After giving mic permissions, it stays black.

**Comment by Sean-Bradley** [comment]
Hi,
I updated the code tonight, 
it's working in my iPhone and Samsung Galaxy Tab, so I think it may now work for your android also.
One problem you will have with not using a PC, is that the XY mode needs Stereo input to draw shapes properly. However, I have created 2 extra mode options to view the waveform and spectrum graphs, and you can also select to draw left or right channel, which gives a better presentation if your only managing to get mono input with your device.
